/**
 * Top-level usage for the bundled CLI entry (`runCliEntry` / `dist/index.js`).
 */
export function printCliUsage(): void {
  process.stdout.write(
    [
      "Usage",
      "  clench [options] <prompt>           One-shot prompt (non-interactive)",
      "  clench [options]                    Interactive REPL when stdin is a TTY",
      "  clench [options] --resume <path>    Slash/status session commands",
      "  clench agents [list|help]           Inspect available agent definitions",
      "  clench skills [list|install <path>|help|<skill> [args]] Inspect, install, or invoke skill definitions",
      "  clench tasks [list|get <task-id>|stop <task-id>|output <task-id>|messages <task-id>|delete <task-id>|create <prompt> [description]|update <task-id> <message>] Inspect in-memory task records",
      "  clench teams [list|get <team-id>|delete <team-id>|create <name> [task-id...]|message <team-id> <message>|run <team-id>] Inspect task teams",
      "  clench crons [list|get <cron-id>|delete <cron-id>|create \"<schedule>\" \"<prompt>\" [description]|create-team \"<schedule>\" <team-id> [description]|disable <cron-id>|run <cron-id>] Inspect cron entries",
      "  clench resume <path|id|latest>      Resume a saved session through slash routing",
      "  clench init                         Bootstrap local repo guidance files",
      "  clench version                      Print local CLI version details",
      "  clench cost                         Show cumulative token and cost usage",
      "  clench diff                         Show git diff for current workspace changes",
      "  clench memory                       Inspect discovered CLAUDE instruction files",
      "  clench model [alias|id]             Print or switch the active model",
      "  clench config <section>             Print merged config for one section",
      "  clench session [list|switch|fork|delete] Manage saved sessions from the CLI",
      "  clench export <path>                Export the resumed session transcript",
      "  clench history [count]              Print recent prompt history",
      "  clench permissions [mode]           Print or set permission mode",
      "  clench compact                      Compact the resumed session",
      "  clench clear --confirm              Clear the resumed session after backup",
      "  clench login                        Start the Claude OAuth login flow",
      "  clench logout                       Clear saved OAuth credentials",
      "  clench doctor                       Print environment and auth diagnostics",
      "  clench sandbox                      Print resolved sandbox status",
      "  clench state                        Print last worker state snapshot",
      "  clench mcp [list|show <server>|help]  Inspect configured MCP servers",
      "  clench plugin [list|install <path>|enable <name>|disable <name>|uninstall <name>|update <name>]",
      "  clench dump-manifests               Print porting workspace manifest JSON",
      "  clench bootstrap-plan <query>       Print a bootstrapped runtime session plan",
      "",
      "Options",
      "  --model <id>              Model alias or full id (default: claude-opus-4-6)",
      "  --permission-mode <mode>  read-only | workspace-write | danger-full-access",
      "  --output-format <fmt>     text | json | ndjson",
      "  --allowed-tools <list>    Comma-separated: bash,grep,glob,read_file,write_file",
      "  --compact                 Print final assistant text only",
      "  --resume <ref|latest>     Session file or latest under .clench/sessions",
      "  --session <ref>         Same resolution as --resume (--resume wins if both)",
      "  --persist                 Persist to .clench/sessions/default.jsonl (no prompt)",
      "  -V, --version             Show local CLI version",
      "  -h, --help                Show this help",
      "",
      "REPL",
      "  Type a message and press Enter. Commands: exit, quit",
      "  History: /history [count] prints recent prompts",
      "  Multi-line: /multiline to start, /submit to send, /cancel to discard",
      "  Shortcut: end a line with \\ to enter multi-line compose mode",
      "  Ctrl-C: cancel current draft or multi-line compose; press again on empty prompt to exit",
      ""
    ].join("\n")
  );
}
